FROM node:14

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Expose the port the app runs on
EXPOSE 5000

# Use the npm script to run the server
CMD ["npm", "run", "server"]