version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
      - db

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=tienhock
      - DB_PASSWORD=foodmaker
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=foodmaker
      - POSTGRES_DB=tienhock
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: