# dev/docker-compose.yml
services:
  dev_app:
    container_name: tienhock_dev_app
    build:
      context: ..
      dockerfile: dev/Dockerfile
    ports:
      - "3000:3000"    
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=http://localhost:5001
    depends_on:
      - dev_server
      - dev_db
    volumes:
      - ..:/app
      - /app/node_modules
    networks:
      - tienhock-dev-network

  dev_server:
    container_name: tienhock_dev_server
    build:
      context: ..
      dockerfile: dev/Dockerfile.server
    ports:
      - "5001:5000"
    environment:
      - DB_USER=postgres
      - DB_HOST=dev_db
      - DB_NAME=tienhock
      - DB_PASSWORD=foodmaker
      - DB_PORT=5432
    env_file:
      - .env
    depends_on:
      - dev_db
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - tienhock-dev-network

  dev_db:
    container_name: tienhock_dev_db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=foodmaker
      - POSTGRES_DB=tienhock
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - tienhock-dev-network

networks:
  tienhock-dev-network:
    name: tienhock-dev-network
    driver: bridge

volumes:
  postgres_dev_data:
    name: tienhock_dev_data