-- Add a shared department lookup for staff forms.
-- Apply: docker exec -i tienhock_dev_db psql -U postgres -d tienhock < migrations/2026_07_07_staff_departments.sql

BEGIN;

CREATE TABLE IF NOT EXISTS departments (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

INSERT INTO departments (id, name)
VALUES
  ('GENERAL WORKER', 'GENERAL WORKER'),
  ('MAINTENANCE', 'MAINTENANCE'),
  ('MACHINE OPERATOR', 'MACHINE OPERATOR'),
  ('SALESMAN', 'SALESMAN'),
  ('MARKETING', 'MARKETING'),
  ('DIRECTOR', 'DIRECTOR'),
  ('LOGISTIC JUNIOR (STOCK)', 'LOGISTIC JUNIOR (STOCK)'),
  ('STOCK & DATA ENTRY CLERK', 'STOCK & DATA ENTRY CLERK'),
  ('BOILERMAN', 'BOILERMAN'),
  ('OPERATION EXECUTIVE', 'OPERATION EXECUTIVE'),
  ('GENERAL CLERK', 'GENERAL CLERK'),
  ('ADMIN', 'ADMIN'),
  ('EXECUTIVE DIRECTOR', 'EXECUTIVE DIRECTOR'),
  ('DRIVER HABUK', 'DRIVER HABUK')
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name;

COMMIT;
