import { SelectOption } from "../components/FormComponents";

export const CURRENCY_OPTIONS: SelectOption[] = [
  { id: "AED", name: "AED - UAE Dirham" },
  { id: "AFN", name: "AFN - Afghani" },
  { id: "ALL", name: "ALL - Lek" },
  { id: "AMD", name: "AMD - Armenian Dram" },
  { id: "ANG", name: "ANG - Netherlands Antillean Guilder" },
  { id: "AOA", name: "AOA - Kwanza" },
  { id: "ARS", name: "ARS - Argentine Peso" },
  { id: "AUD", name: "AUD - Australian Dollar" },
  { id: "AWG", name: "AWG - Aruban Florin" },
  { id: "AZN", name: "AZN - Azerbaijan Manat" },
  { id: "BAM", name: "BAM - Convertible Mark" },
  { id: "BBD", name: "BBD - Barbados Dollar" },
  { id: "BDT", name: "BDT - Taka" },
  { id: "BGN", name: "BGN - Bulgarian Lev" },
  { id: "BHD", name: "BHD - Bahraini Dinar" },
  { id: "BIF", name: "BIF - Burundi Franc" },
  { id: "BMD", name: "BMD - Bermudian Dollar" },
  { id: "BND", name: "BND - Brunei Dollar" },
  { id: "BOB", name: "BOB - Boliviano" },
  { id: "BOV", name: "BOV - Mvdol" },
  { id: "BRL", name: "BRL - Brazilian Real" },
  { id: "BSD", name: "BSD - Bahamian Dollar" },
  { id: "BTN", name: "BTN - Ngultrum" },
  { id: "BWP", name: "BWP - Pula" },
  { id: "BYN", name: "BYN - Belarusian Ruble" },
  { id: "BZD", name: "BZD - Belize Dollar" },
  { id: "CAD", name: "CAD - Canadian Dollar" },
  { id: "CDF", name: "CDF - Congolese Franc" },
  { id: "CHE", name: "CHE - WIR Euro" },
  { id: "CHF", name: "CHF - Swiss Franc" },
  { id: "CHW", name: "CHW - WIR Franc" },
  { id: "CLF", name: "CLF - Unidad de Fomento" },
  { id: "CLP", name: "CLP - Chilean Peso" },
  { id: "CNH", name: "CNH - Yuan Renminbi (International)" },
  { id: "CNY", name: "CNY - Yuan Renminbi (Domestic)" },
  { id: "COP", name: "COP - Colombian Peso" },
  { id: "COU", name: "COU - Unidad de Valor Real" },
  { id: "CRC", name: "CRC - Costa Rican Colon" },
  { id: "CUC", name: "CUC - Peso Convertible" },
  { id: "CUP", name: "CUP - Cuban Peso" },
  { id: "CVE", name: "CVE - Cabo Verde Escudo" },
  { id: "CZK", name: "CZK - Czech Koruna" },
  { id: "DJF", name: "DJF - Djibouti Franc" },
  { id: "DKK", name: "DKK - Danish Krone" },
  { id: "DOP", name: "DOP - Dominican Peso" },
  { id: "DZD", name: "DZD - Algerian Dinar" },
  { id: "EGP", name: "EGP - Egyptian Pound" },
  { id: "ERN", name: "ERN - Nakfa" },
  { id: "ETB", name: "ETB - Ethiopian Birr" },
  { id: "EUR", name: "EUR - Euro" },
  { id: "FJD", name: "FJD - Fiji Dollar" },
  { id: "FKP", name: "FKP - Falkland Islands Pound" },
  { id: "GBP", name: "GBP - Pound Sterling" },
  { id: "GEL", name: "GEL - Lari" },
  { id: "GHS", name: "GHS - Ghana Cedi" },
  { id: "GIP", name: "GIP - Gibraltar Pound" },
  { id: "GMD", name: "GMD - Dalasi" },
  { id: "GNF", name: "GNF - Guinean Franc" },
  { id: "GTQ", name: "GTQ - Quetzal" },
  { id: "GYD", name: "GYD - Guyana Dollar" },
  { id: "HKD", name: "HKD - Hong Kong Dollar" },
  { id: "HNL", name: "HNL - Lempira" },
  { id: "HRK", name: "HRK - Kuna" },
  { id: "HTG", name: "HTG - Gourde" },
  { id: "HUF", name: "HUF - Forint" },
  { id: "IDR", name: "IDR - Rupiah" },
  { id: "ILS", name: "ILS - New Israeli Sheqel" },
  { id: "INR", name: "INR - Indian Rupee" },
  { id: "IQD", name: "IQD - Iraqi Dinar" },
  { id: "IRR", name: "IRR - Iranian Rial" },
  { id: "ISK", name: "ISK - Iceland Krona" },
  { id: "JMD", name: "JMD - Jamaican Dollar" },
  { id: "JOD", name: "JOD - Jordanian Dinar" },
  { id: "JPY", name: "JPY - Yen" },
  { id: "KES", name: "KES - Kenyan Shilling" },
  { id: "KGS", name: "KGS - Som" },
  { id: "KHR", name: "KHR - Riel" },
  { id: "KMF", name: "KMF - Comorian Franc" },
  { id: "KPW", name: "KPW - North Korean Won" },
  { id: "KRW", name: "KRW - Won" },
  { id: "KWD", name: "KWD - Kuwaiti Dinar" },
  { id: "KYD", name: "KYD - Cayman Islands Dollar" },
  { id: "KZT", name: "KZT - Tenge" },
  { id: "LAK", name: "LAK - Lao Kip" },
  { id: "LBP", name: "LBP - Lebanese Pound" },
  { id: "LKR", name: "LKR - Sri Lanka Rupee" },
  { id: "LRD", name: "LRD - Liberian Dollar" },
  { id: "LSL", name: "LSL - Loti" },
  { id: "LYD", name: "LYD - Libyan Dinar" },
  { id: "MAD", name: "MAD - Moroccan Dirham" },
  { id: "MDL", name: "MDL - Moldovan Leu" },
  { id: "MGA", name: "MGA - Malagasy Ariary" },
  { id: "MKD", name: "MKD - Denar" },
  { id: "MMK", name: "MMK - Kyat" },
  { id: "MNT", name: "MNT - Tugrik" },
  { id: "MOP", name: "MOP - Pataca" },
  { id: "MRU", name: "MRU - Ouguiya" },
  { id: "MUR", name: "MUR - Mauritius Rupee" },
  { id: "MVR", name: "MVR - Rufiyaa" },
  { id: "MWK", name: "MWK - Malawi Kwacha" },
  { id: "MXN", name: "MXN - Mexican Peso" },
  { id: "MXV", name: "MXV - Mexican Unidad de Inversion (UDI)" },
  { id: "MYR", name: "MYR - Malaysian Ringgit" },
  { id: "MZN", name: "MZN - Mozambique Metical" },
  { id: "NAD", name: "NAD - Namibia Dollar" },
  { id: "NGN", name: "NGN - Naira" },
  { id: "NIO", name: "NIO - Cordoba Oro" },
  { id: "NOK", name: "NOK - Norwegian Krone" },
  { id: "NPR", name: "NPR - Nepalese Rupee" },
  { id: "NZD", name: "NZD - New Zealand Dollar" },
  { id: "OMR", name: "OMR - Rial Omani" },
  { id: "PAB", name: "PAB - Balboa" },
  { id: "PEN", name: "PEN - Sol" },
  { id: "PGK", name: "PGK - Kina" },
  { id: "PHP", name: "PHP - Philippine Peso" },
  { id: "PKR", name: "PKR - Pakistan Rupee" },
  { id: "PLN", name: "PLN - Zloty" },
  { id: "PYG", name: "PYG - Guarani" },
  { id: "QAR", name: "QAR - Qatari Rial" },
  { id: "RON", name: "RON - Romanian Leu" },
  { id: "RSD", name: "RSD - Serbian Dinar" },
  { id: "RUB", name: "RUB - Russian Ruble" },
  { id: "RWF", name: "RWF - Rwanda Franc" },
  { id: "SAR", name: "SAR - Saudi Riyal" },
  { id: "SBD", name: "SBD - Solomon Islands Dollar" },
  { id: "SCR", name: "SCR - Seychelles Rupee" },
  { id: "SDG", name: "SDG - Sudanese Pound" },
  { id: "SEK", name: "SEK - Swedish Krona" },
  { id: "SGD", name: "SGD - Singapore Dollar" },
  { id: "SHP", name: "SHP - Saint Helena Pound" },
  { id: "SLL", name: "SLL - Leone" },
  { id: "SOS", name: "SOS - Somali Shilling" },
  { id: "SRD", name: "SRD - Surinam Dollar" },
  { id: "SSP", name: "SSP - South Sudanese Pound" },
  { id: "STN", name: "STN - Dobra" },
  { id: "SVC", name: "SVC - El Salvador Colon" },
  { id: "SYP", name: "SYP - Syrian Pound" },
  { id: "SZL", name: "SZL - Lilangeni" },
  { id: "THB", name: "THB - Baht" },
  { id: "TJS", name: "TJS - Somoni" },
  { id: "TMT", name: "TMT - Turkmenistan New Manat" },
  { id: "TND", name: "TND - Tunisian Dinar" },
  { id: "TOP", name: "TOP - Pa'anga" },
  { id: "TRY", name: "TRY - Turkish Lira" },
  { id: "TTD", name: "TTD - Trinidad and Tobago Dollar" },
  { id: "TWD", name: "TWD - New Taiwan Dollar" },
  { id: "TZS", name: "TZS - Tanzanian Shilling" },
  { id: "UAH", name: "UAH - Hryvnia" },
  { id: "UGX", name: "UGX - Uganda Shilling" },
  { id: "USD", name: "USD - US Dollar" },
  { id: "USN", name: "USN - US Dollar (Next day)" },
  { id: "UYI", name: "UYI - Uruguay Peso en Unidades Indexadas (UI)" },
  { id: "UYU", name: "UYU - Peso Uruguayo" },
  { id: "UYW", name: "UYW - Unidad Previsional" },
  { id: "UZS", name: "UZS - Uzbekistan Sum" },
  { id: "VED", name: "VED - Bolivar Soberano" },
  { id: "VES", name: "VES - Bolivar Soberano" },
  { id: "VND", name: "VND - Dong" },
  { id: "VUV", name: "VUV - Vatu" },
  { id: "WST", name: "WST - Tala" },
  { id: "XAF", name: "XAF - CFA Franc BEAC" },
  { id: "XAG", name: "XAG - Silver" },
  { id: "XAU", name: "XAU - Gold" },
  { id: "XBA", name: "XBA - Bond Markets Unit European Composite Unit (EURCO)" },
  { id: "XBB", name: "XBB - Bond Markets Unit European Monetary Unit (E.M.U.-6)" },
  { id: "XBC", name: "XBC - Bond Markets Unit European Unit of Account 9 (E.U.A.-9)" },
  { id: "XBD", name: "XBD - Bond Markets Unit European Unit of Account 17 (E.U.A.-17)" },
  { id: "XCD", name: "XCD - East Caribbean Dollar" },
  { id: "XDR", name: "XDR - SDR (Special Drawing Right)" },
  { id: "XOF", name: "XOF - CFA Franc BCEAO" },
  { id: "XPD", name: "XPD - Palladium" },
  { id: "XPF", name: "XPF - CFP Franc" },
  { id: "XPT", name: "XPT - Platinum" },
  { id: "XSU", name: "XSU - Sucre" },
  { id: "XUA", name: "XUA - ADB Unit of Account" },
  { id: "XXX", name: "XXX - No currency involved" },
  { id: "YER", name: "YER - Yemeni Rial" },
  { id: "ZAR", name: "ZAR - Rand" },
  { id: "ZMW", name: "ZMW - Zambian Kwacha" },
  { id: "ZWL", name: "ZWL - Zimbabwe Dollar" },
];

export const COUNTRY_OPTIONS: SelectOption[] = [
  { id: "ABW", name: "ABW - ARUBA" },
  { id: "AFG", name: "AFG - AFGHANISTAN" },
  { id: "AGO", name: "AGO - ANGOLA" },
  { id: "AIA", name: "AIA - ANGUILLA" },
  { id: "ALA", name: "ALA - ALAND ISLANDS" },
  { id: "ALB", name: "ALB - ALBANIA" },
  { id: "AND", name: "AND - ANDORA" },
  { id: "ANT", name: "ANT - NETHERLANDS ANTILLES" },
  { id: "ARE", name: "ARE - UNITED ARAB EMIRATES" },
  { id: "ARG", name: "ARG - ARGENTINA" },
  { id: "ARM", name: "ARM - ARMENIA" },
  { id: "ASM", name: "ASM - AMERICAN SAMOA" },
  { id: "ATA", name: "ATA - ANTARCTICA" },
  { id: "ATF", name: "ATF - FRENCH SOUTHERN TERRITORIES" },
  { id: "ATG", name: "ATG - ANTIGUA AND BARBUDA" },
  { id: "AUS", name: "AUS - AUSTRALIA" },
  { id: "AUT", name: "AUT - AUSTRIA" },
  { id: "AZE", name: "AZE - AZERBAIDJAN" },
  { id: "BDI", name: "BDI - BURUNDI" },
  { id: "BEL", name: "BEL - BELGIUM" },
  { id: "BEN", name: "BEN - BENIN" },
  { id: "BES", name: "BES - BONAIRE, SINT EUSTATIUS AND SABA" },
  { id: "BFA", name: "BFA - BURKINA FASO" },
  { id: "BGD", name: "BGD - BANGLADESH" },
  { id: "BGR", name: "BGR - BULGARIA" },
  { id: "BHR", name: "BHR - BAHRAIN" },
  { id: "BHS", name: "BHS - BAHAMAS" },
  { id: "BIH", name: "BIH - BOSNIA AND HERZEGOVINA" },
  { id: "BLM", name: "BLM - SAINT BARTHELEMY" },
  { id: "BLR", name: "BLR - BELARUS" },
  { id: "BLZ", name: "BLZ - BELIZE" },
  { id: "BMU", name: "BMU - BERMUDA" },
  { id: "BOL", name: "BOL - BOLIVIA" },
  { id: "BRA", name: "BRA - BRAZIL" },
  { id: "BRB", name: "BRB - BARBADOS" },
  { id: "BRN", name: "BRN - BRUNEI DARUSSALAM" },
  { id: "BTN", name: "BTN - BHUTAN" },
  { id: "BVT", name: "BVT - BOUVET ISLAND" },
  { id: "BWA", name: "BWA - BOTSWANA" },
  { id: "CAF", name: "CAF - CENTRAL AFRICAN REPUBLIC" },
  { id: "CAN", name: "CAN - CANADA" },
  { id: "CCK", name: "CCK - COCOS ISLAND" },
  { id: "CHE", name: "CHE - SWITZERLAND" },
  { id: "CHL", name: "CHL - CHILE" },
  { id: "CHN", name: "CHN - CHINA" },
  { id: "CIV", name: "CIV - COTE D'IVOIRE" },
  { id: "CMR", name: "CMR - CAMEROON" },
  { id: "COD", name: "COD - CONGO, THE DEMOCRATIC REPUBLIC" },
  { id: "COG", name: "COG - CONGO" },
  { id: "COK", name: "COK - COOK ISLANDS" },
  { id: "COL", name: "COL - COLOMBIA" },
  { id: "COM", name: "COM - COMOROS" },
  { id: "CPV", name: "CPV - CABO VERDE" },
  { id: "CRI", name: "CRI - COSTA RICA" },
  { id: "CRM", name: "CRM - CRIMEA" },
  { id: "CUB", name: "CUB - CUBA" },
  { id: "CUW", name: "CUW - CURACAO" },
  { id: "CXR", name: "CXR - CHRISTMAS ISLANDS" },
  { id: "CYM", name: "CYM - CAYMAN ISLANDS" },
  { id: "CYP", name: "CYP - CYPRUS" },
  { id: "CZE", name: "CZE - CZECH REPUBLIC" },
  { id: "DEU", name: "DEU - GERMANY" },
  { id: "DJI", name: "DJI - DJIBOUTI" },
  { id: "DMA", name: "DMA - DOMINICA" },
  { id: "DNK", name: "DNK - DENMARK" },
  { id: "DOM", name: "DOM - DOMINICAN REPUBLIC" },
  { id: "DZA", name: "DZA - ALGERIA" },
  { id: "ECU", name: "ECU - ECUADOR" },
  { id: "EGY", name: "EGY - EGYPT" },
  { id: "ERI", name: "ERI - ERITREA" },
  { id: "ESH", name: "ESH - WESTERN SAHARA" },
  { id: "ESP", name: "ESP - SPAIN" },
  { id: "EST", name: "EST - ESTONIA" },
  { id: "ETH", name: "ETH - ETHIOPIA" },
  { id: "FIN", name: "FIN - FINLAND" },
  { id: "FJI", name: "FJI - FIJI" },
  { id: "FLK", name: "FLK - FALKLAND ISLANDS (MALVINAS)" },
  { id: "FRA", name: "FRA - FRANCE" },
  { id: "FRO", name: "FRO - FAEROE ISLANDS" },
  { id: "FSM", name: "FSM - MICRONESIA, FEDERATED STATES OF" },
  { id: "GAB", name: "GAB - GABON" },
  { id: "GBR", name: "GBR - UNITED KINGDOM" },
  { id: "GEO", name: "GEO - GEORGIA" },
  { id: "GGY", name: "GGY - GUERNSEY" },
  { id: "GHA", name: "GHA - GHANA" },
  { id: "GIB", name: "GIB - GIBRALTAR" },
  { id: "GIN", name: "GIN - GUINEA" },
  { id: "GLP", name: "GLP - GUADELOUPE" },
  { id: "GMB", name: "GMB - GAMBIA" },
  { id: "GNB", name: "GNB - GUINEA-BISSAU" },
  { id: "GNQ", name: "GNQ - EQUATORIAL GUINEA" },
  { id: "GRC", name: "GRC - GREECE" },
  { id: "GRD", name: "GRD - GRENADA" },
  { id: "GRL", name: "GRL - GREENLAND" },
  { id: "GTM", name: "GTM - GUATEMALA" },
  { id: "GUF", name: "GUF - FRENCH GUIANA" },
  { id: "GUM", name: "GUM - GUAM" },
  { id: "GUY", name: "GUY - GUYANA" },
  { id: "HKG", name: "HKG - HONG KONG" },
  { id: "HMD", name: "HMD - HEARD AND MCDONALD ISLANDS" },
  { id: "HND", name: "HND - HONDURAS" },
  { id: "HRV", name: "HRV - CROATIA" },
  { id: "HTI", name: "HTI - HAITI" },
  { id: "HUN", name: "HUN - HUNGARY" },
  { id: "IDN", name: "IDN - INDONESIA" },
  { id: "IMN", name: "IMN - ISLE OF MAN" },
  { id: "IND", name: "IND - INDIA" },
  { id: "IOT", name: "IOT - BRITISH INDIAN OCEAN TERRITORY" },
  { id: "IRL", name: "IRL - IRELAND" },
  { id: "IRN", name: "IRN - IRAN" },
  { id: "IRQ", name: "IRQ - IRAQ" },
  { id: "ISL", name: "ISL - ICELAND" },
  { id: "ISR", name: "ISR - ISRAEL" },
  { id: "ITA", name: "ITA - ITALY" },
  { id: "JAM", name: "JAM - JAMAICA" },
  { id: "JEY", name: "JEY - JERSEY (CHANNEL ISLANDS)" },
  { id: "JOR", name: "JOR - JORDAN" },
  { id: "JPN", name: "JPN - JAPAN" },
  { id: "KAZ", name: "KAZ - KAZAKHSTAN" },
  { id: "KEN", name: "KEN - KENYA" },
  { id: "KGZ", name: "KGZ - KYRGYZSTAN" },
  { id: "KHM", name: "KHM - CAMBODIA" },
  { id: "KIR", name: "KIR - KIRIBATI" },
  { id: "KNA", name: "KNA - ST.KITTS AND NEVIS" },
  { id: "KOR", name: "KOR - THE REPUBLIC OF KOREA" },
  { id: "KWT", name: "KWT - KUWAIT" },
  { id: "LAO", name: "LAO - LAOS" },
  { id: "LBN", name: "LBN - LEBANON" },
  { id: "LBR", name: "LBR - LIBERIA" },
  { id: "LBY", name: "LBY - LIBYAN ARAB JAMAHIRIYA" },
  { id: "LCA", name: "LCA - SAINT LUCIA" },
  { id: "LIE", name: "LIE - LIECHTENSTEIN" },
  { id: "LKA", name: "LKA - SRI LANKA" },
  { id: "LSO", name: "LSO - LESOTHO" },
  { id: "LTU", name: "LTU - LITHUANIA" },
  { id: "LUX", name: "LUX - LUXEMBOURG" },
  { id: "LVA", name: "LVA - LATVIA" },
  { id: "MAC", name: "MAC - MACAO" },
  { id: "MAF", name: "MAF - SAINT MARTIN (FRENCH PART)" },
  { id: "MAR", name: "MAR - MOROCCO" },
  { id: "MCO", name: "MCO - MONACO" },
  { id: "MDA", name: "MDA - MOLDOVA, REPUBLIC OF" },
  { id: "MDG", name: "MDG - MADAGASCAR" },
  { id: "MDV", name: "MDV - MALDIVES" },
  { id: "MEX", name: "MEX - MEXICO" },
  { id: "MHL", name: "MHL - MARSHALL ISLANDS" },
  { id: "MKD", name: "MKD - MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF" },
  { id: "MLI", name: "MLI - MALI" },
  { id: "MLT", name: "MLT - MALTA" },
  { id: "MMR", name: "MMR - MYANMAR" },
  { id: "MNE", name: "MNE - MONTENEGRO" },
  { id: "MNG", name: "MNG - MONGOLIA" },
  { id: "MNP", name: "MNP - NORTHERN MARIANA ISLANDS" },
  { id: "MOZ", name: "MOZ - MOZAMBIQUE" },
  { id: "MRT", name: "MRT - MAURITANIA" },
  { id: "MSR", name: "MSR - MONTSERRAT" },
  { id: "MTQ", name: "MTQ - MARTINIQUE" },
  { id: "MUS", name: "MUS - MAURITIUS" },
  { id: "MWI", name: "MWI - MALAWI" },
  { id: "MYS", name: "MYS - MALAYSIA" },
  { id: "MYT", name: "MYT - MAYOTTE" },
  { id: "NAM", name: "NAM - NAMIBIA" },
  { id: "NCL", name: "NCL - NEW CALEDONIA" },
  { id: "NER", name: "NER - NIGER" },
  { id: "NFK", name: "NFK - NORFOLK ISLAND" },
  { id: "NGA", name: "NGA - NIGERIA" },
  { id: "NIC", name: "NIC - NICARAGUA" },
  { id: "NIU", name: "NIU - NIUE" },
  { id: "NLD", name: "NLD - NETHERLANDS" },
  { id: "NOR", name: "NOR - NORWAY" },
  { id: "NPL", name: "NPL - NEPAL" },
  { id: "NRU", name: "NRU - NAURU" },
  { id: "NZL", name: "NZL - NEW ZEALAND" },
  { id: "OMN", name: "OMN - OMAN" },
  { id: "PAK", name: "PAK - PAKISTAN" },
  { id: "PAN", name: "PAN - PANAMA" },
  { id: "PCN", name: "PCN - PITCAIRN" },
  { id: "PER", name: "PER - PERU" },
  { id: "PHL", name: "PHL - PHILIPPINES" },
  { id: "PLW", name: "PLW - PALAU" },
  { id: "PNG", name: "PNG - PAPUA NEW GUINEA" },
  { id: "POL", name: "POL - POLAND" },
  { id: "PRI", name: "PRI - PUERTO RICO" },
  { id: "PRK", name: "PRK - DEMOC.PEOPLES REP.OF KOREA" },
  { id: "PRT", name: "PRT - PORTUGAL" },
  { id: "PRY", name: "PRY - PARAGUAY" },
  { id: "PSE", name: "PSE - PALESTINIAN TERRITORY, OCCUPIED" },
  { id: "PYF", name: "PYF - FRENCH POLYNESIA" },
  { id: "QAT", name: "QAT - QATAR" },
  { id: "REU", name: "REU - REUNION" },
  { id: "ROU", name: "ROU - ROMANIA" },
  { id: "RUS", name: "RUS - RUSSIAN FEDERATION (USSR)" },
  { id: "RWA", name: "RWA - RWANDA" },
  { id: "SAU", name: "SAU - SAUDI ARABIA" },
  { id: "SCT", name: "SCT - SCOTLAND" },
  { id: "SDN", name: "SDN - SUDAN" },
  { id: "SEN", name: "SEN - SENEGAL" },
  { id: "SGP", name: "SGP - SINGAPORE" },
  { id: "SGS", name: "SGS - SOUTH GEORGIA AND THE SOUTH SANDWICH ISLAND" },
  { id: "SHN", name: "SHN - ST. HELENA" },
  { id: "SJM", name: "SJM - SVALBARD AND JAN MAYEN ISLANDS" },
  { id: "SLB", name: "SLB - SOLOMON ISLANDS" },
  { id: "SLE", name: "SLE - SIERRA LEONE" },
  { id: "SLV", name: "SLV - EL SALVADOR" },
  { id: "SMR", name: "SMR - SAN MARINO" },
  { id: "SOM", name: "SOM - SOMALIA" },
  { id: "SPM", name: "SPM - ST. PIERRE AND MIQUELON" },
  { id: "SRB", name: "SRB - SERBIA" },
  { id: "SSD", name: "SSD - SOUTH SUDAN" },
  { id: "STP", name: "STP - SAO TOME AND PRINCIPE" },
  { id: "SUR", name: "SUR - SURINAME" },
  { id: "SVK", name: "SVK - SLOVAK REPUBLIC" },
  { id: "SVN", name: "SVN - SLOVENIA" },
  { id: "SWE", name: "SWE - SWEDEN" },
  { id: "SWZ", name: "SWZ - ESWATINI, KINGDOM OF (SWAZILAND)" },
  { id: "SXM", name: "SXM - SINT MAARTEN" },
  { id: "SYC", name: "SYC - SEYCHELLES" },
  { id: "SYR", name: "SYR - SYRIAN ARAB REPUBLIC" },
  { id: "TCA", name: "TCA - TURKS AND CAICOS ISLANDS" },
  { id: "TCD", name: "TCD - CHAD" },
  { id: "TGO", name: "TGO - TOGO" },
  { id: "THA", name: "THA - THAILAND" },
  { id: "TJK", name: "TJK - TAJIKISTAN" },
  { id: "TKL", name: "TKL - TOKELAU" },
  { id: "TKM", name: "TKM - TURKMENISTAN" },
  { id: "TLS", name: "TLS - TIMOR-LESTE" },
  { id: "TON", name: "TON - TONGA" },
  { id: "TTO", name: "TTO - TRINIDAD AND TOBAGO" },
  { id: "TUN", name: "TUN - TUNISIA" },
  { id: "TUR", name: "TUR - TURKIYE" },
  { id: "TUV", name: "TUV - TUVALU" },
  { id: "TWN", name: "TWN - TAIWAN" },
  { id: "TZA", name: "TZA - TANZANIA UNITED REPUBLIC" },
  { id: "UGA", name: "UGA - UGANDA" },
  { id: "UKR", name: "UKR - UKRAINE" },
  { id: "UMI", name: "UMI - UNITED STATES MINOR OUTLYING ISLANDS" },
  { id: "URY", name: "URY - URUGUAY" },
  { id: "USA", name: "USA - UNITED STATES OF AMERICA" },
  { id: "UZB", name: "UZB - UZBEKISTAN" },
  { id: "VAT", name: "VAT - VATICAN CITY STATE (HOLY SEE)" },
  { id: "VCT", name: "VCT - SAINT VINCENT AND GRENADINES" },
  { id: "VEN", name: "VEN - VENEZUELA" },
  { id: "VGB", name: "VGB - VIRGIN ISLANDS(BRITISH)" },
  { id: "VIR", name: "VIR - VIRGIN ISLANDS(US)" },
  { id: "VNM", name: "VNM - VIETNAM" },
  { id: "VUT", name: "VUT - VANUATU" },
  { id: "WLF", name: "WLF - WALLIS AND FUTUNA ISLANDS" },
  { id: "WSM", name: "WSM - SAMOA" },
  { id: "XKX", name: "XKX - KOSOVO" },
  { id: "YEM", name: "YEM - YEMEN" },
  { id: "ZAF", name: "ZAF - SOUTH AFRICA" },
  { id: "ZMB", name: "ZMB - ZAMBIA" },
  { id: "ZWE", name: "ZWE - ZIMBABWE" },
];
