services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNGViMjMzOGRiYTEyYTNmNDg3ZTBkMjQyZTQ3YWI2MmUiLCJ0IjoiODhmNGM1MTUtZWQxYi00MzRlLWIzZDctNTBjOTZkNDBjOGZmIiwicyI6Ik5HRmlZakZsWVRVdE4yUmlZeTAwT0dRMExXSm1ZVGN0WVRjMlpXUTVZekU1TURjeCJ9
    depends_on:
      - nginx
    networks:
      - tienhock-prod-network

  nginx:
    build:
      context: ..
      dockerfile: prod/Dockerfile
    container_name: nginx
    environment:
      - REACT_APP_NODE_ENV=production
      - REACT_APP_API_BASE_URL=https://tienhock.com
    depends_on:
      - prod_server
      - prod_db
    networks:
      - tienhock-prod-network

  prod_server:
    container_name: tienhock_prod_server
    build:
      context: ..
      dockerfile: prod/Dockerfile.server
    environment:
      - REACT_APP_NODE_ENV=production
      - HOST=0.0.0.0 # Allow connections from anywhere
      - PORT=5000
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_HOST=prod_db
      - DB_NAME=tienhock_prod
      - DB_PASSWORD=foodmaker
      - DB_PORT=5432
    depends_on:
      - prod_db
    networks:
      tienhock-prod-network:
        aliases:
          - server
    volumes:
      - ../logs:/usr/src/app/logs

  prod_db:
    container_name: tienhock_prod_db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=foodmaker
      - POSTGRES_DB=tienhock_prod
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      tienhock-prod-network:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tienhock-prod-network:
    name: tienhock-prod-network
    driver: bridge

volumes:
  postgres_prod_data:
    name: tienhock_prod_data
