services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - prod_app
      - prod_server
    networks:
      - tienhock-prod-network

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore # Adjust to your timezone
      - SUBDOMAINS=tienhockfood # Replace with your DuckDNS subdomain
      - TOKEN=021f2282-7bf2-4f95-bd18-ff70c4ec84bd # Replace with your DuckDNS token
    networks:
      - tienhock-prod-network

  prod_app:
    container_name: tienhock_prod_app
    build:
      context: ..
      dockerfile: prod/Dockerfile
    environment:
      - REACT_APP_NODE_ENV=production
      - REACT_APP_API_BASE_URL=http://tienhockfood.duckdns.org
      - WDS_SOCKET_PORT=0
    depends_on:
      - prod_server
      - prod_db
    networks:
      - tienhock-prod-network

  prod_server:
    container_name: tienhock_prod_server
    build:
      context: ..
      dockerfile: prod/Dockerfile.server
    environment:
      - REACT_APP_NODE_ENV=production
      - HOST=0.0.0.0 # Allow connections from anywhere
      - DB_USER=postgres
      - DB_HOST=prod_db
      - DB_NAME=tienhock_prod
      - DB_PASSWORD=foodmaker
      - DB_PORT=5432
    depends_on:
      - prod_db
    networks:
      tienhock-prod-network:
        aliases:
          - server
    volumes:
      - ../logs:/usr/src/app/logs

  prod_db:
    container_name: tienhock_prod_db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=foodmaker
      - POSTGRES_DB=tienhock_prod
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      tienhock-prod-network:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tienhock-prod-network:
    name: tienhock-prod-network
    driver: bridge

volumes:
  postgres_prod_data:
    name: tienhock_prod_data
