# prod/docker-compose.template.yml
services: 
  prod_app:
    container_name: tienhock_prod_app
    build:
      context: ..
      dockerfile: prod/Dockerfile
    ports:
      - "192.168.1.200:3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=http://192.168.1.200:5000
    depends_on:
      - prod_server
      - prod_db
    networks:
      - tienhock-prod-network

  prod_server:
    container_name: tienhock_prod_server
    build:
      context: ..
      dockerfile: prod/Dockerfile.server
    ports:
      - "${SERVER_HOST}:5000:5000"
    environment:
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_HOST=prod_db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - HOST=0.0.0.0
      - SERVER_HOST=${SERVER_HOST}
    depends_on:
      - prod_db
    restart: always
    networks:
      tienhock-prod-network:
        aliases:
          - server
    volumes:
      - ../logs:/usr/src/app/logs

  prod_db:
    container_name: tienhock_prod_db
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    ports:
      - "${SERVER_HOST}:5433:5432"
    restart: always
    networks:
      tienhock-prod-network:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tienhock-prod-network:
    name: tienhock-prod-network
    driver: bridge

volumes:
  postgres_prod_data:
    name: tienhock_prod_data