name: Build and Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Create and populate .env file
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYINVOIS_CLIENT_ID: ${{ secrets.MYINVOIS_CLIENT_ID }}
          MYINVOIS_CLIENT_SECRET: ${{ secrets.MYINVOIS_CLIENT_SECRET }}
        run: |
          touch .env
          echo "REACT_APP_API_BASE_URL=http://192.168.1.200:5000" >> .env
          echo "REACT_APP_NODE_ENV=production" >> .env
          echo "REACT_APP_SERVER_PORT=5000" >> .env
          echo "REACT_APP_SERVER_HOST=192.168.1.200" >> .env
          echo "REACT_APP_DB_USER=postgres" >> .env
          echo "REACT_APP_DB_HOST=192.168.1.200" >> .env
          echo "REACT_APP_DB_NAME=tienhock_prod" >> .env
          echo "REACT_APP_DB_PASSWORD=$DB_PASSWORD" >> .env
          echo "REACT_APP_DB_PORT=5433" >> .env
          echo "REACT_APP_MYINVOIS_CLIENT_ID=$MYINVOIS_CLIENT_ID" >> .env
          echo "REACT_APP_MYINVOIS_CLIENT_SECRET=$MYINVOIS_CLIENT_SECRET" >> .env
          
          echo "Verifying .env file exists:"
          ls -a .
        shell: bash

      - name: Build React App
        env:
          CI: false
        run: npm run build

      - name: Build Electron App
        env:
          CI: false
        run: npm run make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            out/make/squirrel.windows/x64/*.exe
          draft: false
          prerelease: false
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
          body: |
            ## What's New

            Release ${{ github.ref_name }} of Tien Hock ERP

            ### Installation
            - For Windows users, download and run `TienHockERP-Setup.exe`
            - The app will automatically check for updates on launch