name: Build and Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Create Environment File
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYINVOIS_CLIENT_ID: ${{ secrets.MYINVOIS_CLIENT_ID }}
          MYINVOIS_CLIENT_SECRET: ${{ secrets.MYINVOIS_CLIENT_SECRET }}
        run: |
          echo "REACT_APP_API_BASE_URL=http://localhost:5000" > .env
          echo "NODE_ENV=production" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_NAME=tienhock_prod" >> .env
          echo "DB_PASSWORD=$env:DB_PASSWORD" >> .env
          echo "DB_PORT=5432" >> .env
          echo "MYINVOIS_API_BASE_URL=https://preprod-api.myinvois.hasil.gov.my" >> .env
          echo "MYINVOIS_CLIENT_ID=$env:MYINVOIS_CLIENT_ID" >> .env
          echo "MYINVOIS_CLIENT_SECRET=$env:MYINVOIS_CLIENT_SECRET" >> .env
          echo "CI=false" >> .env

      - name: Build React App
        env:
          CI: false
        run: npm run build

      - name: Build Electron App
        env:
          CI: false
        run: npm run make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            out/make/squirrel.windows/x64/*.exe
            out/make/zip/win32/x64/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
          body: |
            ## What's New

            Release ${{ github.ref_name }} of Tien Hock ERP

            ### Installation
            - For Windows users, download and run `TienHockERP-Setup.exe`
            - The app will automatically check for updates on launch